apiVersion: v1
kind: Secret
metadata:
  name: expense-tracker-secrets
data:
  PRIVATE_KEY: MzU0NmFzZGZhMDZhNXNhczZkZmdhczU2NGFz
  DB_URL: bW9uZ29kYitzcnY6Ly9tb25nb1VzZXI6VU1lWld3ZmpiS0twejU3dkBjbHVzdGVyMC56bnA2Z2RkLm1vbmdvZGIubmV0L3Rlc3Q/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  REDIS_URL: cmVkaXM6Ly9kZWZhdWx0Om5qaDVCUFBFVnB5RjBIZTlOZldqZ0x3UkRCTW9VZnNzQHJlZGlzLTE2NjQ1LmMyNjQuYXAtc291dGgtMS0xLmVjMi5jbG91ZC5yZWRpc2xhYnMuY29tOjE2NjQ1
  NODE_ENV: cHJvZHVjdGlvbg==
