apiVersion: apps/v1
kind: Deployment

# info about the deployment
metadata:
  name: server-depl
  annotations:
    autoscaling.kubernetes.io/horizontal-pod-autoscaler: "enabled"
    autoscaling.kubernetes.io/horizontal-pod-autoscaler-min: "1"
    autoscaling.kubernetes.io/horizontal-pod-autoscaler-max: "5"
    autoscaling.kubernetes.io/horizontal-pod-autoscaler-cpu-utilization: "2"

# specification of the deployment
spec:
  replicas: 1 # number of replicas

  # specification of the pod selector
  selector:
    matchLabels:
      app: server

  # specification of the pod template
  template:
    metadata:
      labels:
        app: server

    # specification of the container that will run inside the pod
    spec:
      containers:
        - name: server
          image: mayukh551/expense-tracker-server:1.0.0
          # environmental variables for the application to run inside this pod
          env:
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: PRIVATE_KEY

            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: DB_URL

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: REDIS_URL

            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secrets
                  key: NODE_ENV

---
# defining service for sending request to the container inside the pod
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  type: NodePort # type of Service
  selector:
    app: server # name of the pod that NodePort will select
  ports:
    - name: server # name of the port
      protocol: TCP
      port: 5000 # port on which NodePort service will recieve web traffic/requests
      targetPort: 5000 # port on which the server application will listen
