name: Test-Backend-App-Feat

on:
  - push
  - pull_request

jobs:
  app-test:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      DB_URL: ${{secrets.DB_URL}}

    steps:
      - uses: actions/checkout@v3
      - name: Uses Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm install
      - name: Test app.js
        run: npm test app.test.js
